### ISSUE TITLE
Issue with @cdk-cloudformation/mongodb-atlas-project v1.0.0

### ISSUE THREAD

**Issue by dboschm** [cdklabs/cdk-cloudformation#190]
Hello, 
I just noticed the latest public extension version of MongoDB::Atlas::Project (v1.1.0.) is not reflected to the @mongodbatlas-awscdk npm packages. Please update them to 1.1.0.

**Comment by mrgrain** [comment]
Hi there `@cdk-cloudformation/mongodb-atlas-project` is deprecated in favor of packages published by MongoDB directly. 

I believe this is the package you are looking for: https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.1/?lang=typescript
