### ISSUE TITLE
Issue with @cdk-cloudformation/mongodb-atlas-cluster

### ISSUE THREAD

**Issue by tobias-zeptio** [cdklabs/cdk-cloudformation#23]
We're trying to use the cdk construct in region eu-west-1.

```
aws cloudformation activate-type \
        --type-name MongoDB::Atlas::Cluster \
        --publisher-id bb989456c78c398a858fef18f2ca1bfc1fbba082 \
        --type RESOURCE \
        --execution-role-arn ROLE_ARN
```

But get this error.

```
An error occurred (TypeNotFoundException) when calling the ActivateType operation: Type with publisherId bb989456c78c398a858fef18f2ca1bfc1fbba082 and typeName MongoDB::Atlas::Cluster not found
```

I works when we try to active this in us-east-1. I guess this means that the type is only published to that region, can you publish it to eu-west-1 as well?

**Comment by esimonov** [comment]
I would love to see this module in ap-southeast-2!

https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/publish-extension-stacksets.html

**Comment by eddie-atkinson** [comment]
@eladb can we get this re-opened? I successfully repro-ed this issue in ap-southeast-2 for both this resource and for the `mongodb-atlas-networkpeering` template. I would like to be able to configure these templates using CDK.

```
aws cloudformation activate-type --type-name MongoDB::Atlas::NetworkPeering \
--publisher-id  bb989456c78c398a858fef18f2ca1bfc1fbba082  \
--type RESOURCE  \
--execution-role-arn <arn> \
--region ap-southeast-2
```
